"use client";
import {useState} from "react";
import type {BlockedBuilder} from "@/src/safety/service";
import type {ReporterStatus} from "@/src/moderation/service";
import styles from "../settings.module.css";
export function SafetyClient({initialBlocked,reports}:{initialBlocked:BlockedBuilder[];reports:ReporterStatus[]}){const[blocked,setBlocked]=useState(initialBlocked);const[notice,setNotice]=useState("");async function unblock(userId:string){setNotice("");const response=await fetch("/api/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"unblock",targetUserId:userId})});if(response.ok){setBlocked((items)=>items.filter((item)=>item.userId!==userId));setNotice("Builder unblocked. Past rooms stay closed.")}else setNotice("That block could not be changed.")}return <><section><div className={styles.sectionHeader}><div><h2>{blocked.length?`${blocked.length} blocked builder${blocked.length===1?"":"s"}`:"No one is blocked"}</h2><p>Use the report action on a profile, project, room, Circle, or message when Buildmates should review something.</p></div></div>{blocked.length?<div className={styles.list}>{blocked.map((item)=><article key={item.userId}><div><strong>{item.displayName}</strong><span>Blocked {new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(item.createdAt)}</span></div><button className={styles.dangerText} type="button" onClick={()=>void unblock(item.userId)}>Unblock</button></article>)}</div>:<div className={styles.empty}><strong>Your blocked list is empty.</strong><p>You can block a builder from any active connection.</p></div>}<p className={styles.liveMessage} role="status" aria-live="polite">{notice}</p></section><section><div className={styles.sectionHeader}><div><h2>Reports you submitted</h2><p>Buildmates shows the review state without exposing another person’s private account details.</p></div></div>{reports.length?<div className={styles.list}>{reports.map(report=><article key={report.reportId}><div><strong>{reasonLabel(report.reasonCode)}</strong><span>{targetLabel(report.targetKind)} · submitted {new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(report.createdAt)}</span></div><span className={styles.badge} data-status={report.status}>{reportStatusLabel(report.status)}</span></article>)}</div>:<div className={styles.empty}><strong>No submitted reports.</strong><p>Reports and their review status will appear here.</p></div>}</section></>}

function reasonLabel(value:string){return ({spam:"Spam",harassment:"Harassment",impersonation:"Impersonation",unsafe_content:"Unsafe content",privacy:"Privacy concern",other:"Other concern"} as Record<string,string>)[value]??"Reported concern"}
function targetLabel(value:string){return ({profile:"Profile",project:"Project",room:"Room",circle:"Circle",message:"Message"} as Record<string,string>)[value]??"Content"}
function reportStatusLabel(value:string){return ({pending:"Under review",reviewing:"Under review",resolved:"Reviewed",dismissed:"Closed",actioned:"Action taken"} as Record<string,string>)[value]??"Submitted"}
