import { getCurrentUser, isAuthResponse, requireApiUser } from "../../../../src/auth/require-user";
import { getPlatformBindings } from "../../../../src/platform/bindings";
import { changeProjectLifecycle, getProjectBySlug, saveProject, type ProjectInput } from "../../../../src/profile-projects/service";
import { requireSameOriginMutation } from "../../../../src/platform/same-origin";

export async function GET(_:Request,context:{params:Promise<{slug:string}>}) { const [{slug},viewer,{DB}]=await Promise.all([context.params,getCurrentUser(),getPlatformBindings()]); try{const project=await getProjectBySlug(DB,slug,viewer?.id??null);return project?Response.json(project,{headers:viewerHeaders()}):Response.json({error:"not_found"},{status:404,headers:viewerHeaders()});}catch{return Response.json({error:"not_found"},{status:404,headers:viewerHeaders()});} }
export async function PATCH(request:Request,context:{params:Promise<{slug:string}>}) { const origin=requireSameOriginMutation(request);if(origin)return origin;const [{slug},user,{DB}]=await Promise.all([context.params,requireApiUser(),getPlatformBindings()]); if(isAuthResponse(user))return user; try{const body=await request.json() as ({action?:unknown}&Partial<ProjectInput>); if(body.action!==undefined){if(body.action!=="archive"&&body.action!=="restore"&&body.action!=="delete")return Response.json({error:"invalid_action"},{status:400});await changeProjectLifecycle(DB,user.id,slug,body.action);return Response.json({ok:true});} return Response.json(await saveProject(DB,user.id,body as ProjectInput,slug));}catch(error){return Response.json({error:error instanceof Error?error.message:"invalid_project"},{status:400});} }
export async function DELETE(request:Request,context:{params:Promise<{slug:string}>}) { return PATCH(new Request(request.url,{method:"PATCH",headers:request.headers,body:JSON.stringify({action:"delete"})}),context); }
function viewerHeaders():HeadersInit{return{"cache-control":"private, no-store",vary:"Cookie"}}
