import { expect,test } from "@playwright/test";

test("landing explains the real product and all primary controls work",async({page})=>{await page.goto("/");await expect(page).toHaveTitle("Buildmates");await expect(page.getByRole("heading",{name:/Find your people/})).toBeVisible();await expect(page.getByText(/existing connected apps stay under their own permissions/i)).toBeVisible();await page.getByRole("link",{name:"Discover"}).click();await expect(page).toHaveURL(/\/discover$/);await expect(page.getByRole("heading",{name:/What are people building now/})).toBeVisible()});

test("public discovery, map, graph, and cohorts have honest empty states",async({page})=>{for(const[path,heading]of[["/discover","What are people building now?"],["/map","A map without the pin drop."],["/graph","Follow the work, not the follower count."],["/cohorts","Find density without the noise."]]as const){await page.goto(path);await expect(page.getByRole("heading",{name:heading})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow,`${path} has no horizontal overflow`).toBe(false)}});

test("discovery search preserves a useful no-result state",async({page})=>{await page.goto("/discover");await page.getByLabel("Search builders and projects").fill("a-query-that-cannot-match");await page.getByRole("button",{name:"Search"}).click();await expect(page).toHaveURL(/q=a-query-that-cannot-match/);await expect(page.getByRole("heading",{name:"No strong result yet."})).toBeVisible();await expect(page.getByText(/notify you when someone relevant joins/i)).toBeVisible()});

test("product, privacy, install, and account paths are complete",async({page})=>{for(const[path,heading]of[["/product","Networking that starts with the work."],["/privacy","You decide what becomes a signal."],["/install","One app. A clear first run."],["/account","Enter the builder network."]]as const){await page.goto(path);await expect(page.getByRole("heading",{name:heading})).toBeVisible()}});
