import { readFile,readdir } from "node:fs/promises";import { Miniflare } from "miniflare";import { afterEach,beforeEach,describe,expect,it } from "vitest";import { acceptInvite,createCohort,createInviteLink,getBuildGraph,getCohort,listDiscovery,listLocationGroups,requestCohortMembership,setRelevantBuilderWatch } from "../../apps/web/src/discovery/service";

describe("public discovery and cold-start growth",()=>{let mf:Miniflare;let DB:D1Database;const now=Date.parse("2026-07-15T12:00:00Z");beforeEach(async()=>{mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:["DB"],compatibilityDate:"2026-05-22"});DB=await mf.getD1Database("DB") as D1Database;for(const file of(await readdir("apps/web/drizzle")).filter(name=>name.endsWith(".sql")).sort()){const sql=await readFile(`apps/web/drizzle/${file}`,"utf8");for(const statement of sql.split("--> statement-breakpoint").map(part=>part.trim()).filter(Boolean))await DB.prepare(statement).run()}await DB.prepare("INSERT INTO users(id,status,operator_role,created_at,updated_at)VALUES('public','active','none',?,?),('private','active','none',?,?),('viewer','active','none',?,?),('newcomer','active','none',?,?)").bind(now,now,now,now,now,now,now,now).run();for(const[id,handle]of[["public","public-builder"],["private","private-builder"]])await DB.prepare("INSERT INTO handles(user_id,handle,normalized_handle,created_at)VALUES(?,?,?,?)").bind(id,handle,handle,now).run();await DB.prepare("INSERT INTO profiles(id,user_id,display_name,summary,audience,allow_matching,indexable,coarse_location,published_at,created_at,updated_at)VALUES('pp','public','Public Builder','Building voice retrieval','public',1,1,'Vancouver region',?,?,?),('ps','private','Private Builder','Secret robotics','private',1,0,'Exact secret place',?,?,?)").bind(now,now,now,now,now,now).run();await DB.prepare("INSERT INTO profile_fields(profile_id,field_key,value_json,audience,allow_matching,source_status,provenance,updated_at)VALUES('pp','current_work','\"Voice retrieval\"','public',1,'confirmed','self_reported',?),('pp','needs','\"Private need\"','private',1,'confirmed','self_reported',?)").bind(now,now).run();await DB.prepare("INSERT INTO projects(id,owner_user_id,slug,title,summary,audience,allow_matching,status,stage,indexable,published_at,created_at,updated_at)VALUES('project-public','public','voice-index','Voice Index','A public spoken-search project','public',1,'active','prototype',1,?,?,?),('project-private','private','hidden-robot','Hidden Robot','Private project text','private',1,'active','prototype',0,?,?,?)").bind(now,now,now,now,now,now).run();await DB.prepare("INSERT INTO project_taxonomy_items(project_id,kind,taxonomy_item_id,created_at)VALUES('project-public','topic','voice-agents',?)").bind(now).run()});afterEach(async()=>mf.dispose());
it("keeps discovery private while aggregating canonical topic IDs and their overlap anonymously",async()=>{const anonymous=await listDiscovery(DB,null,{query:""});expect(anonymous.builders.map(row=>row.handle)).toEqual(["public-builder"]);expect(anonymous.projects.map(row=>row.slug)).toEqual(["voice-index"]);expect(JSON.stringify(anonymous)).not.toContain("Private need");expect(JSON.stringify(anonymous)).not.toContain("Secret robotics");const places=await listLocationGroups(DB,null);expect(places).toEqual([]);
await DB.prepare("INSERT INTO taxonomy_versions(id,version,status,created_at,activated_at)VALUES('tax-graph',999,'active',?,?)").bind(now,now).run();
await DB.prepare("INSERT INTO topics(id,taxonomy_version_id,slug,label)VALUES('topic-work','tax-graph','topic-work','Topic work'),('voice-agents','tax-graph','voice-agents','Voice agents'),('graph-rag','tax-graph','rag','Retrieval augmented generation'),('secret-robotics','tax-graph','robotics','Robotics')").run();
await DB.prepare("INSERT INTO topic_relationships(from_topic_id,to_topic_id,kind,weight_basis_points)VALUES('topic-work','voice-agents','parent',10000)").run();
await DB.prepare("INSERT INTO users(id,status,operator_role,created_at,updated_at)VALUES('public-two','active','none',?,?)").bind(now,now).run();
await DB.prepare("INSERT INTO handles(user_id,handle,normalized_handle,created_at)VALUES('public-two','second-builder','second-builder',?)").bind(now).run();
await DB.prepare("INSERT INTO profiles(id,user_id,display_name,summary,audience,allow_matching,indexable,coarse_location,published_at,created_at,updated_at)VALUES('pt','public-two','Second Builder','Building retrieval tools','public',1,1,'Vancouver region',?,?,?)").bind(now,now,now).run();
await DB.prepare("INSERT INTO projects(id,owner_user_id,slug,title,summary,audience,allow_matching,status,stage,indexable,published_at,created_at,updated_at)VALUES('project-public-two','public-two','speech-loop','Speech Loop','Another public voice project','public',1,'active','prototype',1,?,?,?),('project-public-three','public-two','retrieval-kit','Retrieval Kit','A public retrieval project','public',1,'active','prototype',1,?,?,?)").bind(now,now,now+200,now,now,now+100).run();
await DB.prepare("INSERT INTO project_taxonomy_items(project_id,kind,taxonomy_item_id,created_at)VALUES('project-public-two','topic','voice-agents',?),('project-public-two','topic','graph-rag',?),('project-public-three','topic','graph-rag',?),('project-private','topic','secret-robotics',?)").bind(now,now,now,now).run();
await DB.prepare("INSERT INTO profile_topic_contributions(user_id,topic_id,updated_at)VALUES('private','topic-work',?)").bind(now).run();
const graph=await getBuildGraph(DB,null);expect(graph.topics).toEqual(expect.arrayContaining([expect.objectContaining({id:"topic-work",builderCount:3,projectCount:2,broaderBuilderCount:1}),expect.objectContaining({id:"voice-agents",builderCount:2,projectCount:2,broaderBuilderCount:2}),expect.objectContaining({id:"graph-rag",builderCount:1,projectCount:2}),expect.objectContaining({id:"secret-robotics",builderCount:1,projectCount:1})]));expect(graph.edges).toEqual([expect.objectContaining({sourceId:"graph-rag",targetId:"voice-agents",builderCount:1})]);expect(JSON.stringify(graph)).not.toContain("project-public");expect(JSON.stringify(graph)).not.toContain("hidden-robot")});
it("supports empty search, cohort membership, bounded invites, and later-relevance watches",async()=>{expect((await listDiscovery(DB,"viewer",{query:"no-such-work"})).builders).toEqual([]);const cohort=await createCohort(DB,"public",{name:"Voice builders",slug:"voice-builders",description:"People building conversational voice systems",visibility:"public"});await expect(requestCohortMembership(DB,"viewer",cohort.id)).resolves.toEqual({status:"active"});expect((await getCohort(DB,"voice-builders","viewer"))?.viewerStatus).toBe("active");const invite=await createInviteLink(DB,"public",{kind:"cohort_admin",targetId:cohort.id,maximumUses:1});await expect(acceptInvite(DB,invite.token,"newcomer")).resolves.toMatchObject({cohortSlug:"voice-builders"});await expect(acceptInvite(DB,invite.token,"private")).rejects.toThrow("invite_not_found");expect(await setRelevantBuilderWatch(DB,"viewer",true)).toEqual({enabled:true});expect(await DB.prepare("SELECT revoked_at AS revokedAt FROM watches WHERE user_id='viewer' AND kind='relevant_builder' AND target_id='network'").first()).toMatchObject({revokedAt:null})});
it("keeps private cohort rosters from invitees and authorizes every targeted invite",async()=>{const cohort=await createCohort(DB,"public",{name:"Quiet builders",slug:"quiet-builders",description:"An invitation-only working group",visibility:"private"});await DB.prepare("INSERT INTO cohort_memberships(cohort_id,user_id,role,status)VALUES(?,?,'member','invited')").bind(cohort.id,"viewer").run();const invited=await getCohort(DB,"quiet-builders","viewer");expect(invited?.viewerStatus).toBe("invited");expect(invited?.members).toEqual([]);await expect(createInviteLink(DB,"viewer",{kind:"builder",targetId:"pp"})).rejects.toThrow("forbidden");await expect(createInviteLink(DB,"viewer",{kind:"connection_card",targetId:"project-public"})).rejects.toThrow("forbidden");await expect(createInviteLink(DB,"public",{kind:"builder",targetId:"pp"})).resolves.toHaveProperty("token");await expect(createInviteLink(DB,"public",{kind:"connection_card",targetId:"project-public"})).resolves.toHaveProperty("token");await expect(createInviteLink(DB,"public",{kind:"connection_card"})).rejects.toThrow("invalid_invite_target");await expect(createInviteLink(DB,"public",{kind:"personal",targetId:"pp"})).rejects.toThrow("invalid_invite_target")});
},30_000);
