import {readFile,readdir} from "node:fs/promises";
import {Miniflare} from "miniflare";
import {afterEach,beforeEach,describe,expect,it} from "vitest";
import {blockBuilder,listBlockedBuilders,reportTarget,unblockBuilder} from "../../apps/web/src/safety/service";

describe("safety controls",()=>{let mf:Miniflare;let DB:D1Database;const now=Date.parse("2026-07-15T12:00:00Z");
beforeEach(async()=>{mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:["DB"],compatibilityDate:"2026-05-22"});DB=await mf.getD1Database("DB") as D1Database;for(const file of (await readdir("apps/web/drizzle")).filter((name)=>name.endsWith(".sql")).sort()){const sql=await readFile(`apps/web/drizzle/${file}`,"utf8");for(const statement of sql.split("--> statement-breakpoint").map((part)=>part.trim()).filter(Boolean))await DB.prepare(statement).run()}await DB.prepare("INSERT INTO users (id,status,operator_role,created_at,updated_at) VALUES ('alice','active','none',?,?),('bob','active','none',?,?)").bind(now,now,now,now).run();await DB.prepare("INSERT INTO profiles (id,user_id,display_name,summary,audience,allow_matching,published_at,created_at,updated_at) VALUES ('pa','alice','Alice','A','public',1,?,?,?),('pb','bob','Bob','B','public',1,?,?,?)").bind(now,now,now,now,now,now).run();await DB.prepare("INSERT INTO match_pairs (id,user_a_id,user_b_id,created_at) VALUES ('pair','alice','bob',?)").bind(now).run();await DB.prepare("INSERT INTO match_proposals (id,match_pair_id,attempt_number,evidence_version_a,evidence_version_b,acceptance_mode_a,acceptance_mode_b,explanation_a_json,explanation_b_json,state,expires_at,created_at) VALUES ('proposal','pair',1,1,1,'manual','manual','{}','{}','pending',?,?)").bind(now+60_000,now).run();await DB.prepare("INSERT INTO matches (id,match_pair_id,proposal_id,matched_at) VALUES ('match','pair','proposal',?)").bind(now).run();await DB.prepare("INSERT INTO connections (id,match_pair_id,match_id,state,created_at,updated_at) VALUES ('connection','pair','match','active',?,?)").bind(now,now).run();await DB.prepare("INSERT INTO rooms (id,match_pair_id,connection_id,status,created_at,updated_at) VALUES ('room','pair','connection','active',?,?)").bind(now,now).run()});afterEach(async()=>mf.dispose());
it("blocks idempotently and invalidates the active relationship",async()=>{await blockBuilder(DB,{actorId:"alice",targetUserId:"bob",now});await blockBuilder(DB,{actorId:"alice",targetUserId:"bob",now:now+1});expect(await listBlockedBuilders(DB,"alice")).toHaveLength(1);expect((await DB.prepare("SELECT state FROM match_proposals WHERE id='proposal'").first<{state:string}>())?.state).toBe("invalidated");expect((await DB.prepare("SELECT state FROM connections WHERE id='connection'").first<{state:string}>())?.state).toBe("blocked");expect((await DB.prepare("SELECT status FROM rooms WHERE id='room'").first<{status:string}>())?.status).toBe("ended");await unblockBuilder(DB,{actorId:"alice",targetUserId:"bob",now:now+2});expect(await listBlockedBuilders(DB,"alice")).toEqual([]);expect((await DB.prepare("SELECT state FROM connections WHERE id='connection'").first<{state:string}>())?.state).toBe("blocked")});
it("opens a moderation case only for a reportable target",async()=>{const result=await reportTarget(DB,{actorId:"alice",targetKind:"profile",targetId:"pb",reasonCode:"privacy",details:"Contains private material",now});expect(result.reportId).toBeTruthy();expect((await DB.prepare("SELECT COUNT(*) AS count FROM moderation_cases").first<{count:number}>())?.count).toBe(1);await expect(reportTarget(DB,{actorId:"alice",targetKind:"profile",targetId:"pa",reasonCode:"other",now})).rejects.toThrow("target_not_found")});
});
