"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import styles from "./inbox.module.css";
type Item={id:string;kind:string;delivery:string;payload:Record<string,unknown>;readAt:number|null;createdAt:number};
type Page={notifications:Item[];newestCursor:string|null;oldestCursor:string|null;hasMore:boolean};
export function InboxClient(){const[items,setItems]=useState<Item[]>([]);const[state,setState]=useState<"loading"|"ready"|"error">("loading");const[hasMore,setHasMore]=useState(false);const[notice,setNotice]=useState("");const newest=useRef<string|null>(null);const oldest=useRef<string|null>(null);
const load=useCallback(async(mode:"initial"|"newer"|"older"="initial")=>{try{const cursor=mode==="newer"?newest.current:mode==="older"?oldest.current:null;const query=cursor?`?${mode==="older"?"before":"after"}=${encodeURIComponent(cursor)}`:"";const response=await fetch(`/api/notifications${query}`,{cache:"no-store"});if(!response.ok)throw new Error();const page=await response.json() as Page;if(mode==="initial")setItems(page.notifications);else setItems(current=>merge(mode==="newer"?[...page.notifications,...current]:[...current,...page.notifications]));if(mode!=="older"&&page.newestCursor)newest.current=page.newestCursor;if(page.oldestCursor)oldest.current=page.oldestCursor;if(mode!=="newer")setHasMore(page.hasMore);setState("ready")}catch{if(mode==="initial")setState("error")}},[]);
useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const poll=window.setInterval(()=>void load("newer"),15_000);return()=>{window.clearTimeout(initial);window.clearInterval(poll)}},[load]);
async function markRead(id:string){const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({notificationId:id})});if(response.ok)setItems(current=>current.map(item=>item.id===id?{...item,readAt:Date.now()}:item))}
async function appeal(item:Item){const caseId=typeof item.payload.caseId==="string"?item.payload.caseId:null;if(!caseId)return;const statement=window.prompt("Explain why this outcome should be reviewed again (20 characters minimum):")?.trim();if(!statement)return;const response=await fetch("/api/moderation-status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId,statement})});setNotice(response.ok?"Appeal received.":"This outcome is not currently appealable.")}
if(state==="loading")return <div className={styles.state} role="status">Loading activity…</div>;if(state==="error")return <div className={styles.state}><h2>Inbox unavailable</h2><p>Your activity is still stored. Check your connection and try again.</p><button onClick={()=>void load()}>Try again</button></div>;if(!items.length)return <div className={styles.state}><h2>Nothing waiting</h2><p>New introductions and account activity will appear here. You do not need to keep this page open.</p><a href="/matches">See recommended builders</a></div>;
return <><section className={styles.list} aria-label="Notifications">{items.map(item=><article key={item.id} className={item.readAt?styles.read:styles.unread}><span className={styles.mark} aria-hidden="true"/><div><p>{label(item.kind)}</p><h2>{summary(item)}</h2><time dateTime={new Date(item.createdAt).toISOString()}>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(item.createdAt)}</time>{linkFor(item)&&<a href={linkFor(item)!}>{linkLabel(item)}</a>}</div><div>{item.kind==="moderation_outcome"&&<button onClick={()=>void appeal(item)}>Appeal outcome</button>}{!item.readAt&&<button onClick={()=>void markRead(item.id)}>Mark read</button>}</div></article>)}</section>{hasMore&&<button className={styles.loadMore} onClick={()=>void load("older")}>Load earlier activity</button>}<p className={styles.notice} role="status" aria-live="polite">{notice}</p></>}
function merge(items:Item[]){const seen=new Set<string>();return items.filter(item=>!seen.has(item.id)&&Boolean(seen.add(item.id))).sort((a,b)=>b.createdAt-a.createdAt||b.id.localeCompare(a.id))}
function label(kind:string){return kind.replaceAll("_"," ")}
function summary(item:Item){if(item.kind==="match_opened")return"Your introduction room is ready.";if(item.kind.includes("message"))return"A connection sent a new message.";if(item.kind.includes("invite"))return"You have a new invitation.";if(item.kind.includes("schedule"))return"A scheduling proposal changed.";if(item.kind==="moderation_outcome")return`A safety review resulted in ${String(item.payload.action??"an account action").replaceAll("_"," ")}.`;return typeof item.payload.message==="string"?item.payload.message:"There is new activity in Buildmates."}
function linkFor(item:Item){if(typeof item.payload.roomId==="string")return`/rooms/${encodeURIComponent(item.payload.roomId)}`;if(typeof item.payload.circleId==="string")return`/circles/${encodeURIComponent(item.payload.circleId)}`;if(item.kind.includes("match"))return"/matches";return null}
function linkLabel(item:Item){if(typeof item.payload.roomId==="string")return"Open room";if(typeof item.payload.circleId==="string")return"Open Circle";return"Review matches"}
