"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import styles from "./inbox.module.css";
type Item={id:string;kind:string;delivery:string;payload:Record<string,unknown>;readAt:number|null;createdAt:number};
type Page={notifications:Item[];newestCursor:string|null;oldestCursor:string|null;hasMore:boolean};
export function InboxClient(){const[items,setItems]=useState<Item[]>([]);const[state,setState]=useState<"loading"|"ready"|"error">("loading");const[hasMore,setHasMore]=useState(false);const[notice,setNotice]=useState("");const newest=useRef<string|null>(null);const oldest=useRef<string|null>(null);
const load=useCallback(async(mode:"initial"|"newer"|"older"="initial")=>{try{const cursor=mode==="newer"?newest.current:mode==="older"?oldest.current:null;const query=cursor?`?${mode==="older"?"before":"after"}=${encodeURIComponent(cursor)}`:"";const response=await fetch(`/api/notifications${query}`,{cache:"no-store"});if(!response.ok)throw new Error();const page=await response.json() as Page;if(mode==="initial")setItems(page.notifications);else setItems(current=>merge(mode==="newer"?[...page.notifications,...current]:[...current,...page.notifications]));if(mode!=="older"&&page.newestCursor)newest.current=page.newestCursor;if(page.oldestCursor)oldest.current=page.oldestCursor;if(mode!=="newer")setHasMore(page.hasMore);setState("ready")}catch{if(mode==="initial")setState("error")}},[]);
useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const poll=window.setInterval(()=>void load("newer"),15_000);return()=>{window.clearTimeout(initial);window.clearInterval(poll)}},[load]);
async function markRead(id:string){const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"read_one",notificationId:id})});if(response.ok)setItems(current=>current.map(item=>item.id===id?{...item,readAt:Date.now()}:item));else setNotice("That activity could not be marked as read.")}
async function markAllRead(){const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"read_all"})});if(response.ok){const readAt=Date.now();setItems(current=>current.map(item=>item.readAt?item:{...item,readAt}));setNotice("All activity marked as read.")}else setNotice("Activity could not be updated.")}
async function appeal(item:Item){const caseId=typeof item.payload.caseId==="string"?item.payload.caseId:null;if(!caseId)return;const statement=window.prompt("Explain why this outcome should be reviewed again (20 characters minimum):")?.trim();if(!statement)return;const response=await fetch("/api/moderation-status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId,statement})});setNotice(response.ok?"Appeal received.":"This outcome is not currently appealable.")}
if(state==="loading")return <div className={styles.state} role="status">Loading activity…</div>;if(state==="error")return <div className={styles.state}><h2>Inbox unavailable</h2><p>Your activity is still stored. Check your connection and try again.</p><button onClick={()=>void load()}>Try again</button></div>;if(!items.length)return <div className={styles.state}><h2>Nothing waiting</h2><p>New introductions and account activity will appear here. You do not need to keep this page open.</p><a href="/matches">See recommended builders</a></div>;
return <><div className={styles.toolbar}>{items.some(item=>!item.readAt)&&<button type="button" onClick={()=>void markAllRead()}>Mark all read</button>}</div><section className={styles.list} aria-label="Notifications">{items.map(item=><article key={item.id} className={item.readAt?styles.read:styles.unread} style={{opacity:1}}><span className={styles.mark} aria-hidden="true"/><div><p>{label(item.kind)}</p><h2>{summary(item)}</h2><time dateTime={new Date(item.createdAt).toISOString()}>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(item.createdAt)}</time>{linkFor(item)&&<a href={linkFor(item)!}>{linkLabel(item)}</a>}</div><div>{item.kind==="moderation_outcome"&&<button onClick={()=>void appeal(item)}>Appeal outcome</button>}{!item.readAt&&<button onClick={()=>void markRead(item.id)}>Mark read</button>}</div></article>)}</section>{hasMore&&<button className={styles.loadMore} onClick={()=>void load("older")}>Load earlier activity</button>}<p className={styles.notice} role="status" aria-live="polite">{notice}</p></>}
function merge(items:Item[]){const seen=new Set<string>();return items.filter(item=>!seen.has(item.id)&&Boolean(seen.add(item.id))).sort((a,b)=>b.createdAt-a.createdAt||b.id.localeCompare(a.id))}
function label(kind:string){return({match_opened:"Introduction ready",new_message:"New message",circle_message:"Circle message",circle_invitation:"Circle invitation",project_collaboration_invite:"Project invitation",meeting_proposed:"Meeting proposal",meeting_response:"Meeting update",connection_reminder:"Reconnect reminder",reconnect_requested:"Reconnect request",renewed_relevance:"Relevant again",room_upgraded:"Room upgraded",moderation_outcome:"Safety review"}as Record<string,string>)[kind]??"Buildmates activity"}
function summary(item:Item){if(item.kind==="match_opened")return"Your private introduction room is ready.";if(item.kind==="new_message")return"A Connection sent you a message.";if(item.kind==="circle_message")return"A member posted in your Circle.";if(item.kind==="circle_invitation")return"You were invited to a Circle.";if(item.kind==="project_collaboration_invite")return"You were invited to collaborate on a project.";if(item.kind==="meeting_proposed")return"A Connection proposed a time to talk.";if(item.kind==="meeting_response")return item.payload.response==="accepted"?"Your meeting proposal was accepted.":"Your meeting proposal was declined.";if(item.kind==="connection_reminder")return"Your private reminder to reconnect is due.";if(item.kind==="reconnect_requested")return"A previous Connection wants to reconnect.";if(item.kind==="renewed_relevance")return"A Connection published work that may be relevant to you again.";if(item.kind==="room_upgraded")return"A shared tool is now active in your room.";if(item.kind==="moderation_outcome")return"A safety review has an update for your account.";return"There is new activity in Buildmates."}
function linkFor(item:Item){if(typeof item.payload.roomId==="string")return`/rooms/${encodeURIComponent(item.payload.roomId)}`;if(typeof item.payload.circleId==="string")return`/circles/${encodeURIComponent(item.payload.circleId)}`;if(typeof item.payload.connectionId==="string")return`/connections#${encodeURIComponent(item.payload.connectionId)}`;if(item.kind==="project_collaboration_invite"&&typeof item.payload.slug==="string")return`/projects/${encodeURIComponent(item.payload.slug)}/collaboration`;if(item.kind.includes("match"))return"/matches";return null}
function linkLabel(item:Item){if(typeof item.payload.roomId==="string")return item.kind.startsWith("meeting_")?"Review time":"Open room";if(typeof item.payload.circleId==="string")return"Open Circle";if(typeof item.payload.connectionId==="string")return"Open connection";if(item.kind==="project_collaboration_invite")return"Review project invitation";return"Review matches"}
