INSERT OR IGNORE INTO topics (id,taxonomy_version_id,slug,label) VALUES
('fintech','taxonomy-buildmates-v1','fintech','Fintech'),
('health-tech','taxonomy-buildmates-v1','health-tech','Health tech'),
('digital-health','taxonomy-buildmates-v1','digital-health','Digital health'),
('wellness-tech','taxonomy-buildmates-v1','wellness-tech','Wellness tech'),
('clinical-ai','taxonomy-buildmates-v1','clinical-ai','Clinical AI'),
('health-data','taxonomy-buildmates-v1','health-data','Health data'),
('biotech-tools','taxonomy-buildmates-v1','biotech-tools','Biotech tools'),
('climate-tech','taxonomy-buildmates-v1','climate-tech','Climate tech'),
('energy-tech','taxonomy-buildmates-v1','energy-tech','Energy tech'),
('climate-data','taxonomy-buildmates-v1','climate-data','Climate data'),
('carbon-accounting','taxonomy-buildmates-v1','carbon-accounting','Carbon accounting'),
('circular-economy','taxonomy-buildmates-v1','circular-economy','Circular economy'),
('sustainable-hardware','taxonomy-buildmates-v1','sustainable-hardware','Sustainable hardware'),
('gaming','taxonomy-buildmates-v1','gaming','Gaming'),
('gaming-ai','taxonomy-buildmates-v1','gaming-ai','Gaming AI'),
('game-development','taxonomy-buildmates-v1','game-development','Game development'),
('multiplayer-systems','taxonomy-buildmates-v1','multiplayer-systems','Multiplayer systems'),
('interactive-storytelling','taxonomy-buildmates-v1','interactive-storytelling','Interactive storytelling'),
('payment-infrastructure','taxonomy-buildmates-v1','payment-infrastructure','Payment infrastructure'),
('fraud-risk','taxonomy-buildmates-v1','fraud-risk','Fraud and risk'),
('banking-infrastructure','taxonomy-buildmates-v1','banking-infrastructure','Banking infrastructure'),
('personal-finance','taxonomy-buildmates-v1','personal-finance','Personal finance'),
('computer-vision','taxonomy-buildmates-v1','computer-vision','Computer vision'),
('human-robot-interaction','taxonomy-buildmates-v1','human-robot-interaction','Human-robot interaction'),
('autonomous-systems','taxonomy-buildmates-v1','autonomous-systems','Autonomous systems'),
('motion-design','taxonomy-buildmates-v1','motion-design','Motion design'),
('generative-media','taxonomy-buildmates-v1','generative-media','Generative media'),
('brand-systems','taxonomy-buildmates-v1','brand-systems','Brand systems'),
('ecommerce','taxonomy-buildmates-v1','ecommerce','E-commerce'),
('logistics-tech','taxonomy-buildmates-v1','logistics-tech','Logistics tech'),
('trust-safety','taxonomy-buildmates-v1','trust-safety','Trust and safety'),
('consumer-ai','taxonomy-buildmates-v1','consumer-ai','Consumer AI'),
('retrieval-evaluation','taxonomy-buildmates-v1','retrieval-evaluation','Retrieval evaluation');
--> statement-breakpoint
DELETE FROM topic_relationships WHERE from_topic_id='payments' AND to_topic_id='fintech' AND kind='parent';
--> statement-breakpoint
INSERT OR IGNORE INTO topic_relationships (from_topic_id,to_topic_id,kind,weight_basis_points) VALUES
('health-tech','digital-health','parent',10000),('health-tech','wellness-tech','parent',10000),('health-tech','clinical-ai','parent',10000),('health-tech','health-data','parent',10000),('health-tech','biotech-tools','parent',10000),
('climate-tech','energy-tech','parent',10000),('climate-tech','climate-data','parent',10000),('climate-tech','carbon-accounting','parent',10000),('climate-tech','circular-economy','parent',10000),('climate-tech','sustainable-hardware','parent',10000),
('gaming','gaming-ai','parent',10000),('gaming','game-development','parent',10000),('gaming','multiplayer-systems','parent',10000),('gaming','interactive-storytelling','parent',10000),
('fintech','payments','parent',10000),('fintech','payment-infrastructure','parent',10000),('fintech','fraud-risk','parent',10000),('fintech','banking-infrastructure','parent',10000),('fintech','personal-finance','parent',10000),
('robotics-hardware','computer-vision','parent',10000),('robotics-hardware','human-robot-interaction','parent',10000),('robotics-hardware','autonomous-systems','parent',10000),
('design-creative','motion-design','parent',10000),('design-creative','generative-media','parent',10000),('design-creative','brand-systems','parent',10000),
('marketplaces-commerce','ecommerce','parent',10000),('marketplaces-commerce','logistics-tech','parent',10000),('marketplaces-commerce','trust-safety','parent',10000),
('ai','consumer-ai','parent',10000),('retrieval-augmented-generation','retrieval-evaluation','parent',10000);
