import { z } from "zod";
import { requireApiUser } from "@/src/auth/require-user";
import { getPlatformBindings } from "@/src/platform/bindings";
import { requireSameOriginMutation } from "@/src/platform/same-origin";
const readSchema=z.object({notificationId:z.string().min(1).max(160)}).strict();
export async function GET(request:Request){const user=await requireApiUser();if(user instanceof Response)return user;const {DB}=await getPlatformBindings();const url=new URL(request.url);const after=parseCursor(url.searchParams.get("after"));const before=parseCursor(url.searchParams.get("before"));let statement;if(after)statement=DB.prepare("SELECT id,kind,delivery,payload_json AS payloadJson,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? AND (created_at>? OR (created_at=? AND id>?)) ORDER BY created_at DESC,id DESC LIMIT 50").bind(user.id,after.createdAt,after.createdAt,after.id);else if(before)statement=DB.prepare("SELECT id,kind,delivery,payload_json AS payloadJson,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT 50").bind(user.id,before.createdAt,before.createdAt,before.id);else statement=DB.prepare("SELECT id,kind,delivery,payload_json AS payloadJson,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 50").bind(user.id);const rows=await statement.all<{id:string;kind:string;delivery:string;payloadJson:string;readAt:number|null;createdAt:number}>();const items=rows.results.map((row)=>({...row,payload:safePayload(row.payloadJson),payloadJson:undefined}));return Response.json({notifications:items,newestCursor:items[0]?cursorFor(items[0]):after?cursorFor(after):null,oldestCursor:items.length?cursorFor(items[items.length-1]!):before?cursorFor(before):null,hasMore:items.length===50},{headers:{"cache-control":"private, no-store"}})}
export async function POST(request:Request){const origin=requireSameOriginMutation(request);if(origin)return origin;const user=await requireApiUser();if(user instanceof Response)return user;const parsed=readSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"invalid_request"},{status:400});const {DB}=await getPlatformBindings();const result=await DB.prepare("UPDATE notifications SET read_at=COALESCE(read_at,?) WHERE id=? AND user_id=?").bind(Date.now(),parsed.data.notificationId,user.id).run();if(Number(result.meta?.changes??0)!==1)return Response.json({error:"not_found"},{status:404});return Response.json({read:true})}
function safePayload(value:string){try{const parsed=JSON.parse(value);return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{}}catch{return {}}}
function cursorFor(value:{createdAt:number;id:string}){return `${value.createdAt}:${encodeURIComponent(value.id)}`}
function parseCursor(value:string|null){if(!value)return null;const split=value.indexOf(":");if(split<1)return null;const createdAt=Number(value.slice(0,split));if(!Number.isSafeInteger(createdAt)||createdAt<0)return null;try{return{createdAt,id:decodeURIComponent(value.slice(split+1))}}catch{return null}}
