const ERROR_MESSAGES: Readonly<Record<string, string>> = {
  authentication_required: "Sign in to continue.",
  forbidden: "You do not have permission to do that.",
  same_origin_required: "For your security, refresh this page before trying again.",
  rate_limited: "Too many attempts. Wait a moment, then try again.",
  handle_unavailable: "That profile address is already in use.",
  invalid_handle: "Use 3 to 32 letters, numbers, or underscores for your profile address.",
  invalid_project: "Review the project fields and try again.",
  invalid_taxonomy_item: "One selected topic, tool, or domain is no longer available.",
  taxonomy_item_not_approved: "One selected topic, tool, or domain is no longer available.",
  duplicate_taxonomy_item: "Remove the duplicate topic, tool, or domain.",
  project_not_found: "This project is no longer available.",
  surface_conflict: "This page changed in another session. Refresh before trying again.",
  invalid_surface_spec: "The generated design did not pass validation. Ask Codex to revise it.",
  identity_link_required: "Connect Buildmates in Codex before continuing.",
  invite_not_found: "This invitation is no longer available.",
  invite_expired: "This invitation has expired.",
  invalid_token: "This invitation link is not valid.",
  recipient_not_found: "No active builder has that handle.",
  invalid_recipient: "Choose another builder. You cannot invite yourself.",
  blocked: "This invitation cannot be sent.",
  invite_already_pending: "An active invitation has already been sent to this builder.",
  invalid_invite_kind: "Choose a supported invitation type.",
  invalid_invite_target: "Choose an active profile or project for this invitation.",
  target_not_found_or_not_authorized: "This page is no longer available to follow.",
  invalid_target: "This page is no longer available to follow.",
  positive_feedback_required: "Share positive introduction feedback before proposing a room upgrade.",
  room_not_found: "This room is no longer available.",
  invalid_availability_window: "Choose a future availability window with an end after its start.",
  availability_window_not_found: "That availability window was already removed.",
  invalid_meeting_time: "Choose a future meeting time.",
  meeting_not_found: "That meeting proposal was already answered or withdrawn.",
  modules_required: "Choose at least one shared tool.",
  upgrade_not_found: "That room upgrade was already answered or withdrawn.",
  module_not_found: "That shared tool is no longer active.",
  entry_not_found: "That entry was changed or removed. Refresh and try again.",
  entry_payload_invalid: "Complete the required field and use a valid web link where requested.",
  invite_invalid: "Invite an active builder who is already connected to you.",
  invite_blocked: "This invitation cannot be sent.",
  invitation_blocked: "This invitation is no longer available.",
  invitation_unavailable: "This invitation has already been answered or withdrawn.",
  user_not_found: "No active builder has that handle.",
  circle_unavailable: "This Circle is no longer available.",
  proposal_unavailable: "This proposal is no longer available.",
  proposal_not_approved: "This proposal has not completed the Circle's approval process.",
  module_unavailable: "That shared tool is no longer active.",
  message_invalid: "Write a message between 1 and 4,000 characters.",
  message_id_conflict: "That send request already saved different text. Check the conversation before sending your revised message.",
  message_rate_limited: "You have sent too many messages. Wait a moment, then try again.",
  room_blocked: "Messages are unavailable for this connection.",
  reminder_not_found: "That reminder has already been dismissed or is no longer available.",
  owner_required: "Only the Circle owner can make this change.",
  owner_protected: "Transfer ownership before changing the owner's membership.",
  transfer_owner_first: "Transfer ownership before leaving this Circle.",
  transfer_failed: "Ownership was not transferred. Refresh the member list and try again.",
  member_unavailable: "That member is no longer available for this change.",
  surface_spec_invalid: "This generated design could not be previewed. Codex can retry from the safe starter design.",
  surface_revision_missing: "The design preview could not be found. Create a new preview and try again.",
  surface_asset_size_invalid: "Use a PNG or JPEG up to 12 MB.",
  surface_asset_signature_mismatch: "The file contents do not match its image type.",
  surface_asset_signature_forbidden: "Use a valid PNG or JPEG image.",
  surface_asset_type_forbidden: "Use a PNG or JPEG image.",
  surface_asset_quota_exceeded: "Your project artwork storage is full.",
  surface_asset_not_owned: "That image is not available in your account.",
  profile_project_not_approved: "That project changed. Refresh and choose it again.",
  profile_project_media_invalid: "Choose a project and add a clear image description.",
  module_payload_invalid: "Choose a supported shared tool and provide a title.",
  rules_payload_invalid: "Add a title and description for the proposed rules.",
  payload_too_large: "This entry is too large. Shorten it and try again.",
  account_assets_unavailable: "Your account assets could not be reached. Try again.",
  account_deletion_conflict: "Account deletion could not start. Try again.",
  actor_not_active: "Your Buildmates account is unavailable for changes.",
};

export function userFacingError(value: unknown, fallback: string): string {
  return typeof value === "string" && ERROR_MESSAGES[value]
    ? ERROR_MESSAGES[value]
    : fallback;
}
