import { isAuthResponse,requireApiUser } from "../../../src/auth/require-user";
import { createInviteLink,listInvites,revokeInvite } from "../../../src/discovery/service";
import { getPlatformBindings } from "../../../src/platform/bindings";
import { requireSameOriginMutation } from "../../../src/platform/same-origin";
const kinds=new Set(["personal","builder","connection_card"]);
export async function GET(){const user=await requireApiUser();if(isAuthResponse(user))return user;const{DB}=await getPlatformBindings();try{return Response.json({invites:await listInvites(DB,user.id)},{headers:{"cache-control":"private, no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){const origin=requireSameOriginMutation(request);if(origin)return origin;const user=await requireApiUser();if(isAuthResponse(user))return user;try{const body=await request.json() as {kind:string;targetId?:string;recipientHandle?:string;maximumUses?:number};if(!kinds.has(body.kind))throw new Error("invalid_invite_kind");const{DB}=await getPlatformBindings();return Response.json(await createInviteLink(DB,user.id,{...body,kind:body.kind as "personal"|"builder"|"connection_card"}),{status:201})}catch(error){return failure(error)}}
export async function DELETE(request:Request){const origin=requireSameOriginMutation(request);if(origin)return origin;const user=await requireApiUser();if(isAuthResponse(user))return user;try{const id=new URL(request.url).searchParams.get("id");if(!id)throw new Error("invite_not_found");const{DB}=await getPlatformBindings();return Response.json(await revokeInvite(DB,user.id,id))}catch(error){return failure(error)}}
function failure(error:unknown){const message=error instanceof Error?error.message:"invite_failed";return Response.json({error:message},{status:message==="forbidden"?403:message.includes("rate_limited")?429:400})}
