import type{Metadata}from"next";
import Link from"next/link";
import{ProductFooter,ProductHeader}from"../../components/discovery/ProductHeader";
import{requireUser}from"../../src/auth/require-user";
import{getHome}from"../../src/discovery/service";
import{getPlatformBindings}from"../../src/platform/bindings";
import styles from"../info.module.css";
export const metadata:Metadata={title:"Home",robots:{index:false,follow:false}};
export default async function HomePage(){const[user,{DB}]=await Promise.all([requireUser("/home"),getPlatformBindings()]);const home=await getHome(DB,user.id);const counts=(home.counts??{})as Record<string,number>;const updated=(home.profile as{updatedAt?:number}|null)?.updatedAt;const pulseExpiry=(home.pulse as{expiresAt?:number}|null)?.expiresAt;const next=!home.profile?{href:"/onboarding",label:"Finish your profile"}:!home.pulse?{href:"/onboarding",label:"Set your Networking Pulse"}:{href:"/matches",label:"Review recommendations"};return <main className={styles.page}><ProductHeader signedIn/><article className={styles.article}><h1>Your builder network.</h1><p className={styles.lead}>Start with the one action that keeps your current work and networking intent useful.</p><div className={styles.status}><strong>Next action</strong><Link href={next.href}>{next.label}</Link></div><section><h2>Freshness</h2><div><p>Profile: {updated?`updated ${new Date(updated).toLocaleDateString()}`:"not published"}</p><p>Networking Pulse: {pulseExpiry?`active until ${new Date(pulseExpiry).toLocaleDateString()}`:"not configured"}</p><p>Relevant-builder watch: {home.watch?"on":"off"}</p><Link href="/invite">Manage watch and invitations</Link></div></section><section><h2>Your network</h2><div><ul><li><Link href="/matches">{Number(counts.matches??0)} pending matches</Link></li><li><Link href="/connections">{Number(counts.connections??0)} active connections</Link></li><li><Link href="/connections">{Number(counts.rooms??0)} active rooms</Link></li><li><Link href="/circles">{Number(counts.circles??0)} active Circles</Link></li></ul></div></section></article><ProductFooter/></main>}
