import type{Metadata}from"next";
import Link from"next/link";
import{ProductFooter,ProductHeader}from"../../components/discovery/ProductHeader";
import{requireUser}from"../../src/auth/require-user";
import{getHome}from"../../src/discovery/service";
import{getPlatformBindings}from"../../src/platform/bindings";
import styles from"./home.module.css";
export const metadata:Metadata={title:"Home",robots:{index:false,follow:false}};
export default async function HomePage(){const[user,{DB}]=await Promise.all([requireUser("/home"),getPlatformBindings()]);const home=await getHome(DB,user.id);const counts=(home.counts??{})as Record<string,number>;const updated=(home.profile as{updatedAt?:number}|null)?.updatedAt;const pulseExpiry=(home.pulse as{expiresAt?:number}|null)?.expiresAt;const next=!home.profile?{href:"/onboarding",label:"Finish your profile"}:!home.pulse?{href:"/onboarding",label:"Set your Networking Pulse"}:{href:"/matches",label:"Review recommendations"};return <main className={styles.page}><ProductHeader signedIn/><article className={styles.dashboard}><section className={styles.intro}><p className={styles.eyebrow}>Your home</p><h1>Your builder network.</h1><p className={styles.lead}>Keep your profile current, review new introductions, and pick up conversations where you left off.</p><div className={styles.next}><span>Up next</span><Link href={next.href}>{next.label}<b aria-hidden="true">↗</b></Link></div></section><section className={styles.network} aria-labelledby="network-title"><div className={styles.sectionHeading}><p>At a glance</p><h2 id="network-title">Your network</h2></div><ul><li><Link href="/matches"><span>Matches to review</span><strong>{Number(counts.matches??0)}</strong></Link></li><li><Link href="/connections"><span>Connections</span><strong>{Number(counts.connections??0)}</strong></Link></li><li><Link href="/connections"><span>Open rooms</span><strong>{Number(counts.rooms??0)}</strong></Link></li><li><Link href="/circles"><span>Circles</span><strong>{Number(counts.circles??0)}</strong></Link></li></ul></section><section className={styles.freshness} aria-labelledby="freshness-title"><div className={styles.sectionHeading}><p>Profile status</p><h2 id="freshness-title">Freshness</h2></div><dl><div><dt>Profile</dt><dd>{updated?`Updated ${new Date(updated).toLocaleDateString()}`:"Not published"}</dd></div><div><dt>Networking Pulse</dt><dd>{pulseExpiry?`Active until ${new Date(pulseExpiry).toLocaleDateString()}`:"Not configured"}</dd></div><div><dt>Relevant-builder watch</dt><dd>{home.watch?"Included in Work Pulse":"Not included"}</dd></div></dl><Link href="/invite">Manage invitations and Work Pulse</Link></section></article><ProductFooter/></main>}
